### ISSUE TITLE
Start fresh in case of AttempRecovery?

### ISSUE THREAD

**Issue by ank700** [ethz-asl/ethzasl_ptam#85]
Hello ,
Sometimes, ptam looses features and tries to attempt for recovery by looking for features corresponding to the previous keyframes. In this case, I want it to remember the last pose before 'tracking loss', then, look for new features in the current image (based on the previous initialization) and start tracking again, so that I don't have to move back and try to re-localize whenever I loose track.

 Can someone tell me if this is even possible?

Thank you

**Comment by stephanweiss** [comment]
a rudimentary function of this behavior is implemented and used if you enable "AutoInit" in the dynamic reconfigure GUI. Pressing "r" in the PTAM preview will then hard reset the map, pressing "a" will soft reset the map and will try to re-use the previous information after re-init. The same soft reset happens if PTAM tracks less than "TrackingQualityFoundPixels" set in the reconfigure GUI.

Hope this helps.

Best,

Stephan

---

Von: ank700 notifications@github.com
Gesendet: Dienstag, 14. Juni 2016 09:54
An: ethz-asl/ethzasl_ptam
Betreff: [ethz-asl/ethzasl_ptam] Start fresh in case of AttempRecovery? (#85)

Hello,
Sometimes, ptam looses features and tries to attempt for recovery by looking for features corresponding to the previous keyframes. In this case, I want it to remember the last pose before 'tracking loss', then, look for new features in the current image (based on the previous initialization) and start tracking again, so that I don't have to move back and try to re-localize whenever I loose track.

Can someone tell me if this is even possible?

Thank you

##
